services:
  labenv:
    image: sh3b0/labenv:vm
    container_name: labenv
    ports:
      - "3000:3000"
    environment:
      - SHELL=/usr/bin/fish
    volumes:
      - /app/workshop:/app/workshop
      - /home/vagrant:/home/ubuntu
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab_net

  firefox:
    image: jlesage/firefox:v25.12.5
    container_name: firefox
    ports:
      - "5800:5800"
    volumes:
      - /home/vagrant/downloads:/config/downloads
    networks:
      - lab_net
    
  typora:
    image: sh3b0/typora:1.12.4
    container_name: typora
    ports:
      - "5801:5800"
    volumes:
      - /home/vagrant/.config/typora:/config/xdg/config/Typora
      - /home/vagrant/docs:/home/ubuntu/docs
    networks:
      - lab_net

networks:
  lab_net:
    name: lab_net
